# DO NOT REMOVE THIS
theme = "hugo-theme-codex"

# Override these settings with your own
title = "Rahul Krishna D"
languageCode = "en-us"
baseURL = "https://rk585.tech/"
copyright = "© 2020"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-162847450-2"

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/rahulkrishna585"
  github = "https://github.com/rk779"
  email = "mailto:rk@rk585.tech"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  gitlab = "https://gitlab.com/rk779"
  instagram = "https://instagram.com/rk585"
  linkedin = "https://linkedin.com/in/rk585"
  telegram = "https://t.me/rk585"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # name and description for meta tags
  name = "Rahul Krishna D"
  description = "Personal website for Rahul Krishna (rk585)"

  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Email", "Gitlab", "Instagram", "LinkedIn", "Telegram"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = "downloads"
  name = "downloads"
  title = "Downloads"
  url = "https://dl.rk585.tech/"
